package net.kyma

import net.kyma.dm.Rating

class MetadataValues {
    public static final flacFileName = 'test.flac'
    public static final flacTitle = 'flac title'
    public static final flacRate = Rating.TWO_HALF
    public static final flacDate = '2018'
    public static final flacAlbum = 'flac album'
    public static final flacAlbumArtist = 'flac album artist'
    public static final flacArtist = 'flac artist'
    public static final flacComposer = 'flac composer'
    public static final flacConductor = 'flac conductor'
    public static final flacCountry = 'flac country'
    public static final flacCustom1 = 'flac custom1'
    public static final flacCustom2 = 'flac custom2'
    public static final flacCustom3 = 'flac custom3'
    public static final flacCustom4 = 'flac custom4'
    public static final flacCustom5 = 'flac custom5'
    public static final flacDiscNo = '1'
    public static final flacGenre = 'flac genre'
    public static final flacGroup = 'flac group'
    public static final flacInstrument = 'flac instrument'
    public static final flacMood = 'flac mood'
    public static final flacMovement = 'flac movement'
    public static final flacOccasion = 'flac occasion'
    public static final flacOpus = 'flac opus'
    public static final flacOrchestra = 'flac orchestra'
    public static final flacQuality = 'flac quality'
    public static final flacRanking = 'flac ranking'
    public static final flacTempo = 'flac tempo'
    public static final flacTonality = 'flac tonality'
    public static final flacTrack = '1'
    public static final flacWork = 'flac work'
    public static final flacWorkType = 'flac wokr type'
    public static final flacCounter = 0

    public static final mp3FileName = 'test.mp3'
    public static final mp3Title = 'mp3Title'
    public static final mp3Rate = Rating.ONE
    public static final mp3Date = '2018'
    public static final mp3Album = 'mp3 album'
    public static final mp3AlbumArtist = 'mp3 album artist'
    public static final mp3Artist = 'mp3 artist'
    public static final mp3Composer = 'mp3 composer'
    public static final mp3Conductor = 'mp3 conductor'
    public static final mp3Country = 'mp3 country'
    public static final mp3Custom1 = 'mp3 custom1'
    public static final mp3Custom2 = 'mp3 custom2'
    public static final mp3Custom3 = 'mp3 custom3'
    public static final mp3Custom4 = 'mp3 custom4'
    public static final mp3Custom5 = 'mp3 custom5'
    public static final mp3DiscNo = ''
    public static final mp3Genre = 'mp3 genre'
    public static final mp3Group = 'mp3 group'
    public static final mp3Instrument = 'mp3 instrument'
    public static final mp3Mood = 'mp3 mood'
    public static final mp3Movement = 'mp3 movement'
    public static final mp3Occasion = 'mp3 occasion'
    public static final mp3Opus = 'mp3 opus'
    public static final mp3Orchestra = 'mp3 orchestra'
    public static final mp3Quality = 'mp3 quality'
    public static final mp3Ranking = 'mp3 ranking'
    public static final mp3Tempo = 'mp3 tempo'
    public static final mp3Tonality = 'mp3 tonality'
    public static final mp3Track = ''
    public static final mp3Work = 'mp3 work'
    public static final mp3WorkType = 'mp3 workTyp'
    public static final mp3Counter = 0
}
